api/urls.py
from django.urls import path
from django.urls.conf import include

from .views import SpaceAPIView, SpaceDetailView

urlpatterns = [
    path('', SpaceAPIView.as_view()),
    path('<str:slug>', SpaceDetailView.as_view()),
    path('rest-auth/', include('rest_auth.urls')),
    path('rest-auth/registration/', include('rest_auth.registration.urls')),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from spaces.views import CustomPasswordChangeView
from rest_framework.documentation import include_docs_urls
from rest_framework.schemas import get_schema_view

API_TITLE = 'Spaces.ng API'
API_DESCRIPTION = 'A web API for the Spaces.ng mobile APP'
schema_view = get_schema_view(title=API_TITLE)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('accounts/password/change/', CustomPasswordChangeView.as_view(), name='account_password_change'),
    path('accounts/', include('allauth.urls')),
    path('api/docs/', include_docs_urls(title=API_TITLE, description=API_DESCRIPTION)),
    path('api/schema/', schema_view),
    path('', include('spaces.urls')),
]

spaces/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'spaces'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.aboutus, name='aboutus'),
    path('contact/', views.contactus, name='contactus'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('findspace/', views.search, name='search'),
    path('register/', views.register_space, name='register_space'),
    path('register/done/', views.register_space_done, name='register_space_done'),
    path('<slug:space>/', views.space_detail, name='space_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spaces/models.py
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager

# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')

class Spaces(models.Model):
    FOUR = '1-4'
    NINE = '5-9'
    FOURTEEN = '10-14'
    NINETEEN = '15-19'
    TWENTYNINE = '20-29'
    THIRTYPLUS = '30+'

    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
        )
    CAPACITY_CHOICES = [
        (FOUR, '1-4'),
        (NINE, '5-9'),
        (FOURTEEN, '10-14'),
        (NINETEEN, '15-19'),
        (TWENTYNINE, '20-29'),
        (THIRTYPLUS, '30+'),
    ]
    
    name = models.CharField(max_length=64)
    slug = models.SlugField(max_length=200, default='')
    description = models.TextField()
    capacity = models.CharField(max_length=8, choices=CAPACITY_CHOICES, default=FOUR)
    pricing = models.PositiveIntegerField()
    image = models.ImageField(upload_to='images/%Y/%m/%d/', null=True, blank=True)
    state = models.CharField(max_length=64, default='')
    lga = models.CharField(max_length=64, default='')
    address = models.CharField(max_length=256, default='')
    created = models.DateField(auto_now_add=True, db_index=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    rating = models.CharField(max_length=4, default='')
    email = models.CharField(max_length=64, default='')
    facebook = models.CharField(max_length= 64, default='')
    twitter = models.CharField(max_length= 64, default='')
    telephone = models.CharField(max_length= 64, default='')
    instagram = models.CharField(max_length= 64, default='')


    objects = models.Manager()
    published = PublishedManager()
    facilities = TaggableManager(verbose_name="Facilities")
    
    class Meta:
        verbose_name = 'Space'
        verbose_name_plural = 'Spaces'
        ordering = ['-created']

    def __str__(self):
        return f'{self.name} - {self.lga}, {self.state}'

    
    def get_absolute_url(self):
        return reverse('spaces:space_detail', args=[self.slug])



class ContactUs(models.Model):
    name = models.CharField(max_length=64)
    email = models.EmailField(max_length=200)
    telephone = models.CharField(max_length=32)
    subject = models.CharField(max_length=200)
    message = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Feedback"

    def __str__(self):
        return self.name

spaces/forms.py
from django import forms
from django.db.models import fields
from .models import ContactUs, Spaces


class ContactUsForm(forms.ModelForm):
	class Meta:
		model = ContactUs
		fields = '__all__'

class RegisterSpaceForm(forms.ModelForm):
    class Meta:
        model = Spaces
        fields = ('name', 'description', 'capacity', 'pricing', 'image', 'state', 'lga', 'address', 'email', 'facebook', 'twitter', 'telephone', 'instagram', 'facilities')

    def __init__(self, *args, **kwargs):
        super(RegisterSpaceForm, self).__init__(*args, **kwargs)
        self.fields['image'].required = False

spaces/views.py
from django.core import paginator
from django.db.models import Count
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render
from allauth.account.views import PasswordChangeView
from .models import Spaces
from .forms import ContactUsForm, RegisterSpaceForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from django.utils.text import slugify
# Create your views here.

class CustomPasswordChangeView(PasswordChangeView):
    # URL to redirect to once passoword has been reset successfully
    success_url = '/accounts/password/reset/key/done'


def index(request):
    featured_spaces = Spaces.published.order_by('-created')[:5]
    return render(request, 'spaces/index.html', {'featured_spaces': featured_spaces})

def dashboard(request):
    object_list = Spaces.published.all()
    facility_list = Spaces.facilities.most_common()[:5]  # Get the first five most common facilities
    spacecount = Spaces.published.all() # Noted for the sake of counting how many spaces has been published altogether
    
    # For filter purpose
    if ('capacity' in request.GET) and (request.GET['capacity'] != ''):
        capacity = request.GET['capacity']
        object_list = object_list.filter(capacity__search=capacity)
    if ('facilities' in request.GET) and (request.GET['facilities'] != ''):
        filter_list = request.GET['facilities'].split(',')
        for facility in filter_list:
            object_list = object_list.filter(facilities__name__search=facility)
    if ('sort' in request.GET) and (request.GET['sort'] != ''):
        sort_list = ['rating', '-rating', 'created', '-created']  # A list of allowed items to sort by
        sort = request.GET['sort']
        if sort in sort_list:
            object_list = object_list.order_by(sort)

    paginator = Paginator(object_list, 10)  # 2 spaces per page for development purposes. 10 spaces per page on the deployed version
    page = request.GET.get('page')
    try:
        spaces = paginator.page(page)
    except PageNotAnInteger:
        spaces = paginator.page(1)
    except EmptyPage:
        spaces = paginator.page(paginator.num_pages)
    return render(request, 'spaces/dashboard.html', {'spaces': spaces, 'page': page, 'spacecount': spacecount, 'facility_list': facility_list, 'object_list': object_list})

@login_required
def space_detail(request, space):
    space = get_object_or_404(Spaces, slug=space, status='published')
    space_tags_ids = space.facilities.values_list('id', flat=True)
    similar_spaces = Spaces.published.filter(facilities__in=space_tags_ids).exclude(id=space.id)
    similar_spaces = similar_spaces.annotate(same_tags=Count('facilities')).order_by('-same_tags', '-created')[:3]
    return render(request, 'spaces/detail.html', {'space': space, 'similar_spaces': similar_spaces})

def search(request):
    try:
        if 'state' in request.GET:
            state = request.GET['state']
            lga = None
            object_list = []
            stateCount = Spaces.published.filter(state__search=state).count()
            facility_list = Spaces.facilities.most_common()[:5]  # Get the first five most common facilities
            if ('lga' in request.GET) and (request.GET['lga'] != ''):
                lga = request.GET['lga']
                object_list = Spaces.published.filter(state__search=state, lga__search=lga)
            else:
                object_list = Spaces.published.filter(state__search=state)
            if (not state) and (not lga):
                return redirect('spaces:dashboard')
            if ('capacity' in request.GET) and (request.GET['capacity'] != ''):
                capacity = request.GET['capacity']
                object_list = object_list.filter(capacity__search=capacity)
            if ('facilities' in request.GET) and (request.GET.getlist('facilities') != ['']):
                filter_list = request.GET.getlist('facilities')
                for facility in filter_list:
                    object_list = object_list.filter(facilities__name__search=facility)
            if ('sort' in request.GET) and (request.GET['sort'] != ''):
                sort_list = ['rating', '-rating', 'created', '-created']  # A list of allowed items to sort by
                sort = request.GET['sort']
                if sort in sort_list:
                    object_list = object_list.order_by(sort)
            paginator = Paginator(object_list, 10)  # 2 spaces per page for development purposes. 10 spaces per page on the deployed version
            page = request.GET.get('page')
            try:
                results = paginator.page(page)
            except PageNotAnInteger:
                results = paginator.page(1)
            except EmptyPage:
                results = paginator.page(paginator.num_pages)
        else:
            return redirect('spaces:dashboard')
    except:
        return redirect('spaces:dashboard')
    return render(request, 'spaces/search.html', {'results': results, 'state': state, 'lga': lga, 'statecount': stateCount, 'lgacount': object_list, 'facility_list': facility_list})


@login_required
def register_space(request):
    if request.method == 'POST':
        f = RegisterSpaceForm(data=request.POST, files=request.FILES)
        if f.is_valid():
            new_space = f.save(commit=False)
            new_space.slug = slugify(new_space.name)
            new_space.save()
            f.save_m2m()
            return redirect('spaces:register_space_done')
    else:
        f = RegisterSpaceForm()
    return render(request, 'spaces/register_space.html', {'form': f})


@login_required
def register_space_done(request):
    return render(request, 'spaces/register_space_done.html')

def aboutus(request):
    return render(request, 'spaces/aboutus.html')

def contactus(request):
    if request.method == 'POST':
        f = ContactUsForm(request.POST)
        if f.is_valid():
            f.save()
            success = "Thank You! Your message has been submitted sucessfully. We'd get back to you shortly."
            return render(request, 'spaces/contactus.html', {'form': f, 'success': success})
    else:
        f = ContactUsForm()
    return render(request, 'spaces/contactus.html', {'form': f})

spaces/templates/spaces/base.html
{% load static %}
{% load account %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- <link rel="stylesheet" href="assets/css/slick.css"> -->
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" integrity="sha512-PgQMlq+nqFLV4ylk1gwUOgm6CtIIXkKwaIHp/PAIWHzig/lKZSEGKEysh0TCVbHJXCLN7WetD8TFecIky75ZfQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'assets/css/base.css' %}" />
    {% block style %}{% endblock %}
    <title>{% block title %}{% endblock %} | Spaces.NG</title>
  </head>
  <body>
    <div class="header-components">
      <header>
        <div class="logo">
          <p class="logo-name"><a href="{% url 'spaces:index' %}"> Spaces.NG</a></p>
        </div>
        <div class="nav-wrap">
          <nav>
            <ul>
              <li><a href="{% url 'spaces:aboutus' %}"> About Us</li></a>
              <li><a href="{% url 'spaces:contactus' %}"> Contact Us</li></a>
              <button class="register-btn"><a href="{% url 'spaces:register_space' %}">Do you have a space?</a></button>
            </ul>
          </nav>
          <div class="user" id = "user">{% if request.user.is_authenticated %}<a><strong>{{ request.user.username | capfirst }}</strong>&nbsp;&nbsp;&nbsp;</a>{% endif %}   
            <i class="far fa-user-circle"></i>
            {% if request.user.is_authenticated %}
              <ul class="dropdown">
                <li><a href="{% url 'account_password_change' %}">Change Password</a></li>
                <li id="id_logout"><a href="#">Log Out</a></li>
              </ul>
            {% else %}
              <ul class="dropdown">
                <li><a href="{% url 'account_signup' %}">Sign up</a></li>
                <li><a href="{% url 'account_login' %}">Sign in</a></li>
              </ul>
            {% endif %}
          </div>
          <div id="menu-icon">
            <div class="bar" id="bars" onclick="lockScroll();"></div>
          </div>
        </div>
        
      </header>
      <div id = "mobile-nav">
        <ul id="mobile-nav-links">
          <li><a href="{% url 'spaces:aboutus' %}">About Us</a></li>
          <li><a href="{% url 'spaces:contactus' %}">Contact Us</a></li>
          <li><a href="{% url 'spaces:register_space' %}">Register a Space</a></li>
          <li><a href="{% url 'spaces:dashboard' %}">Find a Space</a></li>
        </ul>
      </div>
  </div>
    {% block content %}
    {% endblock %}
    {% if request.user.is_authenticated %}
    <div class="modal-wrap" id="logout-modal">
      <div class="modal">
        <p>Are you sure you want to log out?</p>
        <form action="{% url 'account_logout' %}" method="POST" id="logout-form">
          {% csrf_token %}
          <input type="submit" value="YES, LOG OUT" id="logout">
          <input type="submit" value="No" id="cancel-logout">
        </form>
        <div class="modal-close">
          <p>x</p>
        </div>
      </div>
    </div>
      {% endif %}
    <div class="footer-component">
      <footer>
        <div class="footer-wrap">
          <div class="footer-info">
            <p class="logo-name">Spaces.NG</p>
            <div class="contact">
              <p><i class="fas fa-envelope"></i>spacesng@gmail.com</p>
              <p class="bold-icon"><i class="fas fa-phone-alt"></i>08050040020</p>
              <p class="app"><i class="fab fa-android"></i><a href="#"> Download our Android app</a></p>
            <p class="app"><i class="fab fa-apple"></i>Download our IOS app</p>
            </div>
            
          </div>
          <div class="site-links">
            <h3>Site Links</h3>
            <ul>
              <li><i class="fas fa-arrow-alt-circle-right"></i><a href="{% url 'spaces:aboutus' %}">About Us</a></li>
              <li><i class="fas fa-arrow-alt-circle-right"></i><a href="{% url 'spaces:contactus' %}">Contact Us</a></li>
              <li><i class="fas fa-arrow-alt-circle-right"></i><a href="/api/docs" target="_blank">API documentation</a></li>
            </ul>
          </div>
          <div class="legal">
            <h3>Legal</h3>
            <ul>
              <li><i class="fas fa-arrow-alt-circle-right"></i>Terms & conditions</li>
              <li><i class="fas fa-arrow-alt-circle-right"></i>License Agreement</li>
              <li><i class="fas fa-arrow-alt-circle-right"></i>Privacy Policy</li>
              <li><i class="fas fa-arrow-alt-circle-right"></i>Copyright Information</li>
              <li><i class="fas fa-arrow-alt-circle-right"></i>Cookies Policy</li>
            </ul>       
          </div>
          <div>
            <h3>Social Links</h3>
            <ul class="social">
              <li><i class="fab fa-instagram"></i></li>
              <li><i class="fab fa-facebook"></i></li>
              <li><i class="fab fa-twitter"></i></li>
            </ul>
          </div>
        </div>
      </footer>
      <div class="pjt-92">
        <p>Designed by PJT-92 Team</p>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <script src="{% static 'assets/js/base.js' %}"></script>
    {% block domready %}
    {% endblock %}
  </body>
</html>

spaces/templates/spaces/contactus.html
{% extends 'spaces/base.html' %}
{% load static %}
{% block title %}Contact Us{% endblock %}
{% block style %}
<!-- <link rel="stylesheet" href="{% static 'assets/css/signin.css' %}" /> -->
<link rel="stylesheet" href="{% static 'assets/css/contactus.css' %}" />{% endblock %}
{% block content %}
<ul class="contact__nav">
    <li><a href="{% url 'spaces:index' %}">Home</a></li>
    <li><a href="#">Contact Us</a></li>
  </ul>
  <div class="image__container">
    <h1>Contact Us</h1>
    {% if success %}
    <p>{{ success }}</p>
    {% else %}
    <p>We love to hear from you!</p>
    {% endif %}
</div>
  <div class="container">
      <form action="{% url 'spaces:contactus' %}" method="POST" class="contact__form">
          {% csrf_token %}
          <h1 class="heading">Get in Touch</h1>
          <p>Feel free to drop a message below</p>
          <div class="form__container">
              <div class="detail">
                  <input type="text" name="name" id="input__element" required>
                  <label for="name">Full Name</label>
                  <div class="underline"></div>
              </div>
              <div class="detail">
                  <input type="text" name="email" id="input__element" required> 
                  <label for="email">Email</label>
                  <div class="underline"></div>
              </div>
              <div class="detail">
                  <input type="tel" name="telephone" id="input__element" required>
                  <label for="telephone">Phone Number</label>
                  <div class="underline"></div>
              </div>
              <div class="detail">
                  <input type="text" name="subject" id="input__element" required>
                  <label for="subject">Subject</label>
                  <div class="underline"></div>
              </div>
              <div class="detail">
                  <textarea name="message" id="input__element" cols="30" rows="10" required></textarea>
                  <label for="message">Type your message</label>
                  <div class="underline"></div>
              </div>
          </div>

          <button class="btn">Submit</button>
      </form>
      <div class="contact__address">
          <div class="contact__details">
              <h1 class="contact__us">You Can Always Reach Us</h1>
              <div class="call">
                  <i class="phone fa fa-phone-alt"></i>
                  <p class="contact__text">Call: +2348050040020</p>
              </div>
              <div class="mail">
                  <i class="envelope fa fa-envelope"></i>
                  <p class="contact__text">Email: spacesng@gmail.com</p>
              </div>
          </div>
      </div>
  </div>
{% endblock %}
{% block domready %}
<script src="{% static 'assets/js/signin.js' %}"></script>
{% endblock %}

spaces/templates/spaces/dashboard.html
{% extends 'spaces/base.html' %}
{% load static %}
{% block title %}Explore Workspaces{% endblock %}
{% block style %}
<!-- <link rel="stylesheet" href="{% static 'assets/css/signin.css' %}" /> -->
<link rel="stylesheet" href="{% static 'assets/css/dashboard.css' %}" />{% endblock %}
{% block content %}
<div class="main">
    <div class="breadcrumb">
      <ul>
        <li><a href="{% url 'spaces:index' %}">Home</a></li>
        <!-- <li><a href="#">
          <span class="state">Lagos</span> (
          <span class="number-found-state">100</span> )</a>
        </li>
        <li><a href="#">
          Workspaces in <span class="lga">Ikeja</span> (
          <span class="number-found-city">10</span> )</a>
        </li> -->
        <li><a href="{% url 'spaces:dashboard' %}">
            Explore Workspaces {% if spaces %}({{ spacecount.count }}){% endif %}</a>
          </li>
      </ul>
    </div>
    <form action="{% url 'spaces:search' %}" >
      <div class="country form-item">
        <label>Select a Country</label>
        <select name="country" id="country" disabled>
          <option value="Nigeria">Nigeria</option>
        </select>
      </div>
      <div class="state form-item">
        <label>Select a State</label>
        <select name="state" class="state" id="state">
        </select>
      </div>
      <div class="city form-item">
        <label>Select LGA</label>
        <select name="lga" class="lga" id="lga">
          <option value="">Select LGA</option>
        </select>
      </div>
      <button type="submit" id="submit">Find Space</button>
    </form>
    <div class="results-wrap">
      <div class="page-title">
        <!-- <h1>
          Workspaces in <span class="city">Ikeja</span>,<br />
          <span class="state">Lagos</span> State
        </h1> -->
        <h1>
            Explore Workspaces {% if spaces %}({{ spacecount.count }}){% endif %}
          </h1>
      </div>
      <div class="main-body">
        <section class="aside">
         
          <div class="space-filters">
            <div class="facilities space-filters-item">
              <h3 class="aside-item-title">Facilities</h3>
              <div class="filter-wrap close-filter">
                {% for facility in facility_list %}
                <div class="facilities-item">
                  <p>{{ facility | capfirst }}</p>
                  <input type="checkbox" name="{{ facility | lower }}" id="{{ facility | lower | slugify }}" />
                </div>
                {% endfor %}
              </div>
            </div>
            <div class="attendees space-filters-item">
              <h3 class="">Attendees</h3>
              <select name="attendees" id="attendees">
                <option value="">Any</option>
                <option value="1-4">1-4</option>
                <option value="5-10">5-10</option>
                <option value="10-14">10-14</option>
                <option value="15-19">15-19</option>
                <option value="20-29">20-29</option>
                <option value="30+">30+</option>
              </select>
            </div>
          </div>
        </section>
        <section class="results">
          <div class="first">
            <p class="first-line">
              All spaces available
            </p>
            <div class="sort">
              <p>Sort by:</p>
              <select name="Most liked" id="sort">
                <option value="-created">Newest First</option>
                <option value="created">Oldest First</option>
                <option value="-rating">
                  Rating: High to Low
                </option>
                <option value="rating">
                  Rating: Low to High
                </option>
              </select>
            </div>
          </div>
          <div class="second">
            <p>
              <span class="spaces-found">{{ object_list.count }} Space{{ object_list.count|pluralize }} found.</span>
            </p>
          </div>
          <div class="spaces-wrap">
              {% for space in spaces %}
            <a href="{{ space.get_absolute_url }}" data-facilities="{{ space.facilities.all | join:', ' }}">
              <div class="spaces-item">
                <img src="{{ space.image.url }}" alt="" />
                <div class="space-item-text">
                  <p class="space-name">{{ space.name }}</p>
                  <p class="space-item-location">
                    <i class="fas fa-map-marker-alt"></i> {{ space.state }}, Nigeria.
                  </p>
                </div>
                <div class="like-icon"><i class="far fa-heart"></i></div>
                <div class="ratings">
                  <p class="rating-value">{{ space.rating }}</p>
                  <i class="fas fa-star"></i>
                </div>
              </div>
            </a>
            {% empty %}
            <div class="no-results">
            <!-- <img src="assets/img/no-result" alt=""> -->
                <p>Sorry, there are no spaces that match your query.</p>
            </div>
             {% endfor %}
             <!-- end of spaces -->
          </div>
             {% if spaces %}
                {% include "pagination.html" with page=spaces %}
          {% endif %}
        </section>
      </div>
    </div>
  </div>
{% endblock %}
{% block domready %}
<script src="{% static 'assets/js/dashboard.js' %}"></script>
<script src="{% static 'assets/js/signin.js' %}"></script>
<script src="{% static 'assets/js/filter.js' %}"></script>
{% endblock %}

spaces/templates/spaces/register_space.html
{% extends 'spaces/base.html' %}
{% load static %}
{% block title %}Register Your Space{% endblock %}
{% block style %}
<link rel="stylesheet" href="{% static 'assets/css/spaceowner.css' %}" />
<link rel="stylesheet" href="{% static 'assets/css/signin.css' %}" />
{% endblock %}
{% block content %}
<div class="main-wrap">
    <div class="breadcrumb">
      <ul>
        <li><a href="{% url 'spaces:index' %}">Home</a></li>
        <li><a href="">Do you have a space?</a></li>
      </ul>
    </div>
    <div class="main">
      <form target="_blank" action="{% url 'spaces:register_space' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" name="facilities" value="" id="id_facilities">
        <h1>Do you have a space?</h1>
        <h4>Submit your space for listing on our website</h4>
        <section class="info">
          <div class="basic-info">
            <input type="text" name="name" placeholder="Name of space" required>
            <textarea name="description" id="" cols="30" rows="10" placeholder="Space description" required></textarea>
            <div class="facilities">
              <h3>Facilities</h3>
              <div class="checkbox-wrap">
                <div class="checkbox-item">
                  <input type="checkbox" name="waiting-room" id="waiting-room">
                  <p>Waiting room</p>
                </div>
                <div class="checkbox-item">
                  <input type="checkbox" name="Parking" id="Parking">
                  <p>Parking</p>
                </div>
                <div class="checkbox-item">
                  <input type="checkbox" name="wifi" id="wifi">
                  <p>Wifi</p>
                </div>
                <div class="checkbox-item">
                  <input type="checkbox" name="whiteboard" id="whiteboard">
                  <p>Whiteboard</p>
                </div>
                <div class="checkbox-item">
                  <input type="checkbox" name="flat-screen" id="flat-screen">
                  <p>Flat Screen Tv</p>
                </div>
                <div class="checkbox-item">
                  <input type="checkbox" name="restaurant" id="restuarant">
                  <p>Restaurant</p>
                </div>
                <div class="checkbox-item">
                  <input type="checkbox" name="Ensuite Kitchenette" id="Ensuite Kitchenette">
                  <p>Ensuite Kitchenette</p>
                </div>
                
              </div>
              <div class="other-facilities">
                <input type="text" id="other-facilities" placeholder="Other Facilities">
                <button class="add">Add</button>
              </div>
              
            </div>
          </div>
          <div class="other">
            <div class="upload">
              <div class="img-block">
                <!-- <i class="fas fa-images"></i> -->
                <img id="space-image">
              </div>
              <input type="file" name="image" id="img-upload" accept="image/*" onchange="previewImg(event);" required>
              <!-- <button>Upload thumbnail</button> -->
            </div>
            <div class="select-item">
              <label for="capacity">Space capacity</label>
              <select name="capacity" id="capacity" required>
                <option value="1-4">1-4</option>
                <option value="5-9">5-9</option>
                <option value="10-14">10-14</option>
                <option value="15-19">15-19</option>
                <option value="20-29">20-29</option>
                <option value="30+">30+</option>
              </select>
            </div>
            
            <label for="price">Price</label>
            <input name="pricing" type="text" placeholder="Price per hour(N)" required>
            
          </div>
        </section>
        <section class="contact-info">
          <h2>Add Contact Information</h2>
          <select name="state" id="state" required>
            <option value="">Select a state</option>
          </select>
          <select name="lga" id="lga" required>
            <option value="">Select L.G.A</option>
          </select>
          <input name="address" type="text" placeholder="Add Street Address" required>
          <input name="telephone" type="text" placeholder="Add Phone" required>
          <input name="email" type="text" placeholder="Add Email">
          Add Social Media Accounts
          <input name="twitter" type="text" placeholder="Twitter">
          <input name="instagram" type="text" placeholder="Instagram">
          <input name="facebook" type="text" placeholder="Facebook">
          <input type="submit" value="submit" id="submit">
        </section>
        
        
      </form>
      <!-- <form action="" method="post">
        {{ form }}
      </form> -->
    </div>
  </div>
{% endblock %}
{% block domready %}
<script src="{% static 'assets/js/spaceowner.js' %}"></script>
<script src="{% static 'assets/js/signin.js' %}"></script>
{% endblock %}

spaces/templates/spaces/register_space_done.html
{% extends 'spaces/base.html' %}
{% load static %}
{% block title %}Register Your Space{% endblock %}
{% block style %}
<link rel="stylesheet" href="{% static 'assets/css/spaceowner.css' %}" />
<link rel="stylesheet" href="{% static 'assets/css/signin.css' %}" />
{% endblock %}
{% block content %}
<div class="register-success">
    <div class="text-wrap">
      <p>Thank you for registering a space with us. We will send you a mail shortly after confirming your Space.</p>
    <button><a href="{% url 'spaces:index' %}">Back to home</a></button>
    </div>
</div>
{% endblock %}
{% block domready %}
<script src="{% static 'assets/js/index.js' %}"></script>
<script src="{% static 'assets/js/signin.js' %}"></script>
{% endblock %}